### ISSUE TITLE
Slack integrations at limit

### ISSUE THREAD

**Issue by thfield** [sfbrigade/Infrastructure-Team#22]
The CycleReady team at some point started our own channel because we wanted to include integrations but the official sfbrigade channel was at its limit.  I don't remember right now which integrations we wanted, or if we even ended up using them, but I will look into that.  This may turn out to be a non-issue -- we are still trying to figure out how to keep our institutional memory and organize ourselves/issues/direction.  We're starting to use gh issues/wiki a little more and that may be the way to go.

**Comment by jszwedko** [comment]
I would guess that we aren't using more than some of these: https://sfbrigade.slack.com/services , but the integration limit does feel pretty low.

Let us know if you need to make room for an integration, @thfield !

**Comment by jszwedko** [comment]
Closing this since it is stale, but please re-open if you need us to make room for an integration @thfield
