### ISSUE TITLE
Randomize the check-in link

### ISSUE THREAD

**Issue by j6design** [sfbrigade/Infrastructure-Team#25]
Evening,

The check-in link has the embedded question.  Can we randomize the link with the ones below...If we can't randomize, present a different link for each week (sequential ).

https://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin/?event=Hack+Night&question=What+do+you+most+like+doing+at+Hack+Night?

https://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin/?event=Hack+Night&question=Is+this+your+first+Hack+Night?

https://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin/?event=Hack+Night&question=How+did+you+hear+about+us?

https://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin/?event=Hack+Night&question=I+come+to+Code+for+San+Francisco+because?

Thank you!

**Comment by jszwedko** [comment]
Hey!

This should be pretty easy to do via Javascript on page load -- do you have a preferred default for those with JS disabled (generally a minority)?

**Comment by j6design** [comment]
Hey Jesse,

As long as there is a default link incase JS is disabled.

Thanks
Julio

**Comment by j6design** [comment]
Hey Jesse,

Use the first one.

Thanks
Julio

**Comment by jszwedko** [comment]
:+1:

**Comment by jszwedko** [comment]
@j6design created PR to add this, but it did occur to me that we usually direct people directly to the checkin page as part of the Hack Night intro which would bypass this. We'll need to either:
- Start directing them to the Code for SF website and have them click through to check in
- Have the random question logic be part of the checkin app (not sure what this would look like or if it is feasible as that is owned by Code for America and I couldn't find the source)

**Comment by jszwedko** [comment]
Closed via https://github.com/sfbrigade/sfbrigade.github.io/pull/132
