### ISSUE TITLE
Consider adding a Github Issues button to the website

### ISSUE THREAD

**Issue by afomi** [sfbrigade/Infrastructure-Team#9]
-- and or in Brigade Communications

As a User, 
I want to know the place to put Issues,
so I can be assured my feedback is received in the appropriate place.
- Github issues provides status of an Issue over its lifecycle

**Comment by jszwedko** [comment]
:+1: to this

**Comment by jszwedko** [comment]
Moving this to https://github.com/sfbrigade/sfbrigade.github.io
